[package]
name = "macros"
version.workspace = true
edition.workspace = true

[lib]
name = "macros"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
tauri.workspace = true
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true
uuid.workspace = true
rand.workspace = true
slotmap.workspace = true
tokio.workspace = true
spin_sleep.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
evdev.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
enigo.workspace = true
self_update.workspace = true
http.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics.workspace = true
core-foundation.workspace = true
foreign-types.workspace = true

[build-dependencies]
tauri-build.workspace = true
