/* Generated by cbindgen from macros-ffi/src/lib.rs. Do not edit by hand. */

#ifndef MACROS_FFI_H
#define MACROS_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Registers the callback every `tracing` event gets formatted and routed
 * through — call once, before anything else, from the host's main thread
 * (e.g. right at the top of `$on_mod(Loaded)`, before `macros_init`).
 * `callback` receives one already-formatted, NUL-terminated line per
 * event; a null callback is accepted but makes this a no-op (events are
 * still silently dropped, same as before this existed).
 */
void macros_set_log_callback(void (*callback)(const char*));

/**
 * Must be called once, from the host's main thread, before any other
 * `macros_*` function — on macOS the Accessibility prompt
 * (`request_accessibility`) requires the calling thread to be the main
 * thread. `config_dir_override_utf8` may be null/empty to use the OS
 * config directory as-is (the correct default on native Windows and
 * native macOS, where the embedder and any companion editor share one
 * filesystem); pass a path to redirect macro/settings storage elsewhere
 * (e.g. a Wine `Z:`-mapped path to the real desktop app's config dir when
 * running under Proton). `linux_bridge_resource_path_utf8` is the
 * Windows-side path (as `CCFileUtils` resolves it) to the bundled
 * `linux-input.so` resource — only used if this turns out to be running
 * under Wine on a Linux host (Proton); ignored (may be null) otherwise.
 *
 * Returns 0 on success, -1 if no input backend could be created for this
 * platform.
 */
int32_t macros_init(const char *config_dir_override_utf8,
                    const char *linux_bridge_resource_path_utf8);

/**
 * Starts recording into the currently-selected macro's timing baseline.
 * Mirrors the desktop app's `StartRecordingImmediate` hotkey handler.
 */
int32_t macros_start_recording(void);

/**
 * Stops recording and, if anything was captured, appends it to the
 * currently-selected macro's recording target and saves it to disk.
 * Returns the number of instructions captured and saved (0 means the
 * capture hook produced nothing at all — distinct from the negative error
 * codes below, which mean recording state couldn't even be resolved/saved).
 */
int32_t macros_stop_recording(void);

/**
 * Runs a macro on a background thread — the explicit `id_utf8` if given
 * (nullable), otherwise the currently-selected macro, matching the
 * desktop app's `RunMacro`/`RunSpecificMacro` hotkey semantics. Loop mode
 * is read live from the shared settings file on every call, same as the
 * desktop app. Returns immediately; the run continues after this call
 * returns and is interruptible via `macros_stop_loop`.
 *
 * `elapsed_overshoot_ms` (>= 0, milliseconds): how much real time had
 * already passed, before this call, since playback was actually supposed
 * to start — pass 0 if the caller has no such notion. `macros-gd`'s
 * attempt-start trigger only fires once per game frame, so it always
 * overshoots its own grace-period target by that frame's `dt`; passing
 * that overshoot here backdates the run's first `Wait` deadline to the
 * *intended* start instant instead of whenever this call happens to run,
 * via `Macro::run_with_offset`.
 */
int32_t macros_run_macro(const char *id_utf8, double elapsed_overshoot_ms);

/**
 * Stops every in-flight run (single or looping) started via
 * `macros_run_macro`.
 */
int32_t macros_stop_loop(void);

/**
 * Sets the global playback speed multiplier — applied on top of each
 * macro's own per-macro `speed_multiplier` (see `Macro::speed_multiplier`)
 * — mirroring the desktop app's `set_global_speed_multiplier` command.
 * Clamped to `SPEED_MULTIPLIER_RANGE` (0.1x-10x). `macros_run_macro`
 * already reads this fresh from the shared settings file on every call,
 * so this takes effect starting with the next run; it does not speed up
 * or slow down a run already in flight. Always returns 0.
 */
int32_t macros_set_speed_multiplier(double multiplier);

/**
 * Creates a new macro (name defaults to `"New Macro"` if `name_utf8` is
 * null/empty), saves it, and marks it the currently-selected macro —
 * mirroring the desktop app's "+" button (the `new_macro` command).
 * Returns 0 on success, -1 if the new macro couldn't be saved.
 */
int32_t macros_create_macro(const char *name_utf8);

/**
 * Returns a heap-allocated, NUL-terminated UTF-8 JSON array of every saved
 * macro, as `[{"id": "...", "name": "..."}, ...]`, in the same order the
 * desktop app's macro list uses (case-insensitive name, then id). The mod
 * has no delimited-text parser of its own but already carries Geode's
 * bundled `matjson` transitively, so real JSON is handed back rather than
 * inventing a bespoke format. Never null (an empty library serializes to
 * `"[]"`); caller must free the result with `macros_free_string`.
 */
char *macros_list_macros(void);

/**
 * Returns a heap-allocated, NUL-terminated UTF-8 string with the id of the
 * currently-selected macro, or null if none is selected. Caller must free a
 * non-null result with `macros_free_string`.
 */
char *macros_get_selected_macro_id(void);

/**
 * Marks the macro with the given id as the currently-selected one — the
 * target `macros_run_macro(NULL)`, `macros_stop_recording`, and
 * `macros_clear_recording_target_instructions` all resolve against. Returns
 * 0 on success, -1 if no macro with that id exists.
 */
int32_t macros_select_macro(const char *id_utf8);

/**
 * Renames the currently-selected macro and saves it. `name_utf8`'s
 * surrounding whitespace is trimmed; a null/empty/whitespace-only name is
 * rejected rather than silently saving a blank title (unlike the desktop
 * app's own rename field, which has no such guard — but the mod's popup
 * has no live validation feedback, so this is the one place that has to
 * catch it). Returns 0 on success, or a negative error code: -1 no macro
 * currently selected, -2 selected macro couldn't be loaded, -3 the
 * trimmed name was empty, -4 couldn't be saved back to disk.
 */
int32_t macros_rename_macro(const char *name_utf8);

/**
 * Permanently deletes the currently-selected macro's file from disk and
 * clears the selection (mirroring the desktop app's "Remove Macro"
 * button, minus its two-step confirm timer — the mod's own UI puts up its
 * own confirmation before ever calling this). Returns 0 on success, or a
 * negative error code: -1 no macro currently selected, -2 selected macro
 * couldn't be loaded (already gone?), -3 couldn't be removed from disk.
 */
int32_t macros_delete_macro(void);

/**
 * Clears every recorded instruction from the currently-selected macro's
 * recording-target strand only (see `Macro::recording_target_mut`) —
 * unlike the desktop app's "Clear Instructions" button, which wipes every
 * strand in the macro, this leaves every other strand untouched, and keeps
 * the target strand's own `WhenRan`/`BlockHeader` if it has one (so it
 * stays a valid entry point / block body for the next recording instead of
 * disappearing). Returns the number of instructions removed (0 if the
 * strand had none beyond its header), or a negative error code: -1 no
 * macro currently selected, -2 selected macro couldn't be loaded, -3
 * couldn't be saved back to disk.
 */
int32_t macros_clear_recording_target_instructions(void);

/**
 * Frees a string previously returned by `macros_list_macros` or
 * `macros_get_selected_macro_id`. Safe to call with null (no-op).
 */
void macros_free_string(char *ptr);

/**
 * True if input capture/emission couldn't be set up — on macOS this means
 * Accessibility access hasn't been granted (to the host process); the
 * caller should surface a UI prompt to check System Settings.
 */
bool macros_grab_failed(void);

/**
 * Trivial ABI/link smoke-test symbol.
 */
int32_t macros_ping(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MACROS_FFI_H */
