[package]
name = "macros"
version = "0.3.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.23"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
dirs = "6.0.0"
uuid = { version = "1.18.1", features = ["v4"] }
rand = "0.10.1"
slotmap = { version = "1.0.7", features = ["serde"] }
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread", "macros", "sync", "net", "io-util"] }
spin_sleep = "1.3.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
rev = "8df1858"
version = "1.0.0"
default-features = false

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.13.2"
libcosmic = {
    git = "https://github.com/pop-os/libcosmic.git",
    rev = "8df1858",
    version = "1.0.0",
    default-features = false,
    features = [
        #"debug",
        "winit",
        "tokio",
        "xdg-portal",
        "dbus-config",
        "a11y",
        "multi-window",
        "serde-keycode"
    ]
}

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
] }
enigo = "0.6"
libcosmic = {
    git = "https://github.com/pop-os/libcosmic.git",
    rev = "8df1858",
    version = "1.0.0",
    default-features = false,
    features = [
        #"debug",
        "winit",
        "tokio",
        "multi-window",
        "serde-keycode"
    ]
}

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.23"
core-foundation = "0.9"
foreign-types = "0.5"

[build-dependencies]
