use evdev::Key;

use crate::input::types::MacroKey;

/// Maps an evdev Key (from a captured event) to our canonical MacroKey.
pub fn evdev_key_to_macro_key(key: Key) -> Option<MacroKey> {
    Some(match key {
        Key::KEY_A => MacroKey::Unicode('a'),
        Key::KEY_B => MacroKey::Unicode('b'),
        Key::KEY_C => MacroKey::Unicode('c'),
        Key::KEY_D => MacroKey::Unicode('d'),
        Key::KEY_E => MacroKey::Unicode('e'),
        Key::KEY_F => MacroKey::Unicode('f'),
        Key::KEY_G => MacroKey::Unicode('g'),
        Key::KEY_H => MacroKey::Unicode('h'),
        Key::KEY_I => MacroKey::Unicode('i'),
        Key::KEY_J => MacroKey::Unicode('j'),
        Key::KEY_K => MacroKey::Unicode('k'),
        Key::KEY_L => MacroKey::Unicode('l'),
        Key::KEY_M => MacroKey::Unicode('m'),
        Key::KEY_N => MacroKey::Unicode('n'),
        Key::KEY_O => MacroKey::Unicode('o'),
        Key::KEY_P => MacroKey::Unicode('p'),
        Key::KEY_Q => MacroKey::Unicode('q'),
        Key::KEY_R => MacroKey::Unicode('r'),
        Key::KEY_S => MacroKey::Unicode('s'),
        Key::KEY_T => MacroKey::Unicode('t'),
        Key::KEY_U => MacroKey::Unicode('u'),
        Key::KEY_V => MacroKey::Unicode('v'),
        Key::KEY_W => MacroKey::Unicode('w'),
        Key::KEY_X => MacroKey::Unicode('x'),
        Key::KEY_Y => MacroKey::Unicode('y'),
        Key::KEY_Z => MacroKey::Unicode('z'),
        Key::KEY_1 => MacroKey::Unicode('1'),
        Key::KEY_2 => MacroKey::Unicode('2'),
        Key::KEY_3 => MacroKey::Unicode('3'),
        Key::KEY_4 => MacroKey::Unicode('4'),
        Key::KEY_5 => MacroKey::Unicode('5'),
        Key::KEY_6 => MacroKey::Unicode('6'),
        Key::KEY_7 => MacroKey::Unicode('7'),
        Key::KEY_8 => MacroKey::Unicode('8'),
        Key::KEY_9 => MacroKey::Unicode('9'),
        Key::KEY_0 => MacroKey::Unicode('0'),
        Key::KEY_MINUS => MacroKey::Unicode('-'),
        Key::KEY_EQUAL => MacroKey::Unicode('='),
        Key::KEY_LEFTBRACE => MacroKey::Unicode('['),
        Key::KEY_RIGHTBRACE => MacroKey::Unicode(']'),
        Key::KEY_BACKSLASH => MacroKey::Unicode('\\'),
        Key::KEY_SEMICOLON => MacroKey::Unicode(';'),
        Key::KEY_APOSTROPHE => MacroKey::Unicode('\''),
        Key::KEY_GRAVE => MacroKey::Unicode('`'),
        Key::KEY_COMMA => MacroKey::Unicode(','),
        Key::KEY_DOT => MacroKey::Unicode('.'),
        Key::KEY_SLASH => MacroKey::Unicode('/'),
        Key::KEY_ENTER => MacroKey::Return,
        Key::KEY_BACKSPACE => MacroKey::Backspace,
        Key::KEY_TAB => MacroKey::Tab,
        Key::KEY_SPACE => MacroKey::Space,
        Key::KEY_ESC => MacroKey::Escape,
        Key::KEY_DELETE => MacroKey::Delete,
        Key::KEY_INSERT => MacroKey::Insert,
        Key::KEY_HOME => MacroKey::Home,
        Key::KEY_END => MacroKey::End,
        Key::KEY_PAGEUP => MacroKey::PageUp,
        Key::KEY_PAGEDOWN => MacroKey::PageDown,
        Key::KEY_UP => MacroKey::UpArrow,
        Key::KEY_DOWN => MacroKey::DownArrow,
        Key::KEY_LEFT => MacroKey::LeftArrow,
        Key::KEY_RIGHT => MacroKey::RightArrow,
        Key::KEY_LEFTSHIFT => MacroKey::LShift,
        Key::KEY_RIGHTSHIFT => MacroKey::RShift,
        Key::KEY_LEFTCTRL => MacroKey::LControl,
        Key::KEY_RIGHTCTRL => MacroKey::RControl,
        Key::KEY_LEFTALT => MacroKey::Alt,
        Key::KEY_RIGHTALT => MacroKey::AltGr,
        Key::KEY_LEFTMETA => MacroKey::Meta,
        Key::KEY_RIGHTMETA => MacroKey::Meta,
        Key::KEY_CAPSLOCK => MacroKey::CapsLock,
        Key::KEY_NUMLOCK => MacroKey::NumLock,
        Key::KEY_SCROLLLOCK => MacroKey::ScrollLock,
        Key::KEY_PAUSE => MacroKey::Pause,
        Key::KEY_SYSRQ => MacroKey::PrintScr,
        Key::KEY_F1 => MacroKey::F1,
        Key::KEY_F2 => MacroKey::F2,
        Key::KEY_F3 => MacroKey::F3,
        Key::KEY_F4 => MacroKey::F4,
        Key::KEY_F5 => MacroKey::F5,
        Key::KEY_F6 => MacroKey::F6,
        Key::KEY_F7 => MacroKey::F7,
        Key::KEY_F8 => MacroKey::F8,
        Key::KEY_F9 => MacroKey::F9,
        Key::KEY_F10 => MacroKey::F10,
        Key::KEY_F11 => MacroKey::F11,
        Key::KEY_F12 => MacroKey::F12,
        Key::KEY_F13 => MacroKey::F13,
        Key::KEY_F14 => MacroKey::F14,
        Key::KEY_F15 => MacroKey::F15,
        Key::KEY_F16 => MacroKey::F16,
        Key::KEY_F17 => MacroKey::F17,
        Key::KEY_F18 => MacroKey::F18,
        Key::KEY_F19 => MacroKey::F19,
        Key::KEY_F20 => MacroKey::F20,
        Key::KEY_F21 => MacroKey::F21,
        Key::KEY_F22 => MacroKey::F22,
        Key::KEY_F23 => MacroKey::F23,
        Key::KEY_F24 => MacroKey::F24,
        Key::KEY_KP0 => MacroKey::Numpad0,
        Key::KEY_KP1 => MacroKey::Numpad1,
        Key::KEY_KP2 => MacroKey::Numpad2,
        Key::KEY_KP3 => MacroKey::Numpad3,
        Key::KEY_KP4 => MacroKey::Numpad4,
        Key::KEY_KP5 => MacroKey::Numpad5,
        Key::KEY_KP6 => MacroKey::Numpad6,
        Key::KEY_KP7 => MacroKey::Numpad7,
        Key::KEY_KP8 => MacroKey::Numpad8,
        Key::KEY_KP9 => MacroKey::Numpad9,
        Key::KEY_KPPLUS => MacroKey::Add,
        Key::KEY_KPMINUS => MacroKey::Subtract,
        Key::KEY_KPASTERISK => MacroKey::Multiply,
        Key::KEY_KPSLASH => MacroKey::Divide,
        Key::KEY_KPDOT => MacroKey::Decimal,
        Key::KEY_VOLUMEDOWN => MacroKey::VolumeDown,
        Key::KEY_MUTE => MacroKey::VolumeMute,
        Key::KEY_VOLUMEUP => MacroKey::VolumeUp,
        Key::BTN_LEFT => return None,   // handled as MacroButton
        Key::BTN_RIGHT => return None,
        Key::BTN_MIDDLE => return None,
        Key::BTN_BACK | Key::BTN_SIDE => return None,
        Key::BTN_FORWARD | Key::BTN_EXTRA => return None,
        _ => MacroKey::Other(key.0 as u32),
    })
}

/// Maps a MacroButton (from a captured mouse button event) to evdev key for re-emission.
pub fn evdev_button_from_code(code: u16) -> Option<crate::input::types::MacroButton> {
    use crate::input::types::MacroButton;
    Some(match Key(code) {
        Key::BTN_LEFT => MacroButton::Left,
        Key::BTN_RIGHT => MacroButton::Right,
        Key::BTN_MIDDLE => MacroButton::Middle,
        Key::BTN_BACK | Key::BTN_SIDE => MacroButton::Back,
        Key::BTN_FORWARD | Key::BTN_EXTRA => MacroButton::Forward,
        _ => return None,
    })
}

/// Maps our canonical MacroKey to an evdev Key for emission via uinput.
pub fn macro_key_to_evdev(key: &MacroKey) -> Option<(Key, bool)> {
    Some(match key {
        MacroKey::Return => (Key::KEY_ENTER, false),
        MacroKey::Backspace => (Key::KEY_BACKSPACE, false),
        MacroKey::Tab => (Key::KEY_TAB, false),
        MacroKey::Space => (Key::KEY_SPACE, false),
        MacroKey::Escape => (Key::KEY_ESC, false),
        MacroKey::Delete => (Key::KEY_DELETE, false),
        MacroKey::Insert => (Key::KEY_INSERT, false),
        MacroKey::Home => (Key::KEY_HOME, false),
        MacroKey::End => (Key::KEY_END, false),
        MacroKey::PageUp => (Key::KEY_PAGEUP, false),
        MacroKey::PageDown => (Key::KEY_PAGEDOWN, false),
        MacroKey::UpArrow => (Key::KEY_UP, false),
        MacroKey::DownArrow => (Key::KEY_DOWN, false),
        MacroKey::LeftArrow => (Key::KEY_LEFT, false),
        MacroKey::RightArrow => (Key::KEY_RIGHT, false),
        MacroKey::Shift | MacroKey::LShift => (Key::KEY_LEFTSHIFT, false),
        MacroKey::RShift => (Key::KEY_RIGHTSHIFT, false),
        MacroKey::Control | MacroKey::LControl => (Key::KEY_LEFTCTRL, false),
        MacroKey::RControl => (Key::KEY_RIGHTCTRL, false),
        MacroKey::Alt | MacroKey::Option => (Key::KEY_LEFTALT, false),
        MacroKey::AltGr => (Key::KEY_RIGHTALT, false),
        MacroKey::Meta => (Key::KEY_LEFTMETA, false),
        MacroKey::CapsLock => (Key::KEY_CAPSLOCK, false),
        MacroKey::NumLock => (Key::KEY_NUMLOCK, false),
        MacroKey::ScrollLock => (Key::KEY_SCROLLLOCK, false),
        MacroKey::Pause => (Key::KEY_PAUSE, false),
        MacroKey::PrintScr => (Key::KEY_SYSRQ, false),
        MacroKey::F1 => (Key::KEY_F1, false),
        MacroKey::F2 => (Key::KEY_F2, false),
        MacroKey::F3 => (Key::KEY_F3, false),
        MacroKey::F4 => (Key::KEY_F4, false),
        MacroKey::F5 => (Key::KEY_F5, false),
        MacroKey::F6 => (Key::KEY_F6, false),
        MacroKey::F7 => (Key::KEY_F7, false),
        MacroKey::F8 => (Key::KEY_F8, false),
        MacroKey::F9 => (Key::KEY_F9, false),
        MacroKey::F10 => (Key::KEY_F10, false),
        MacroKey::F11 => (Key::KEY_F11, false),
        MacroKey::F12 => (Key::KEY_F12, false),
        MacroKey::F13 => (Key::KEY_F13, false),
        MacroKey::F14 => (Key::KEY_F14, false),
        MacroKey::F15 => (Key::KEY_F15, false),
        MacroKey::F16 => (Key::KEY_F16, false),
        MacroKey::F17 => (Key::KEY_F17, false),
        MacroKey::F18 => (Key::KEY_F18, false),
        MacroKey::F19 => (Key::KEY_F19, false),
        MacroKey::F20 => (Key::KEY_F20, false),
        MacroKey::F21 => (Key::KEY_F21, false),
        MacroKey::F22 => (Key::KEY_F22, false),
        MacroKey::F23 => (Key::KEY_F23, false),
        MacroKey::F24 => (Key::KEY_F24, false),
        MacroKey::Numpad0 => (Key::KEY_KP0, false),
        MacroKey::Numpad1 => (Key::KEY_KP1, false),
        MacroKey::Numpad2 => (Key::KEY_KP2, false),
        MacroKey::Numpad3 => (Key::KEY_KP3, false),
        MacroKey::Numpad4 => (Key::KEY_KP4, false),
        MacroKey::Numpad5 => (Key::KEY_KP5, false),
        MacroKey::Numpad6 => (Key::KEY_KP6, false),
        MacroKey::Numpad7 => (Key::KEY_KP7, false),
        MacroKey::Numpad8 => (Key::KEY_KP8, false),
        MacroKey::Numpad9 => (Key::KEY_KP9, false),
        MacroKey::Add => (Key::KEY_KPPLUS, false),
        MacroKey::Subtract => (Key::KEY_KPMINUS, false),
        MacroKey::Multiply => (Key::KEY_KPASTERISK, false),
        MacroKey::Divide => (Key::KEY_KPSLASH, false),
        MacroKey::Decimal => (Key::KEY_KPDOT, false),
        MacroKey::VolumeDown => (Key::KEY_VOLUMEDOWN, false),
        MacroKey::VolumeMute => (Key::KEY_MUTE, false),
        MacroKey::VolumeUp => (Key::KEY_VOLUMEUP, false),
        MacroKey::LMenu => (Key::KEY_LEFTMETA, false),
        MacroKey::Select => (Key::KEY_SELECT, false),
        MacroKey::Unicode(c) => char_to_evdev(*c)?,
        MacroKey::Other(n) => (Key(*n as u16), false),
    })
}

/// Maps a MacroButton to the corresponding evdev Key code for emission.
pub fn macro_button_to_evdev(button: &crate::input::types::MacroButton) -> Option<Key> {
    use crate::input::types::MacroButton;
    Some(match button {
        MacroButton::Left => Key::BTN_LEFT,
        MacroButton::Right => Key::BTN_RIGHT,
        MacroButton::Middle => Key::BTN_MIDDLE,
        MacroButton::Back => Key::BTN_BACK,
        MacroButton::Forward => Key::BTN_FORWARD,
        MacroButton::Other(n) => Key(*n as u16),
        // Scroll variants are emitted as REL_WHEEL, not KEY events
        MacroButton::ScrollUp
        | MacroButton::ScrollDown
        | MacroButton::ScrollLeft
        | MacroButton::ScrollRight => return None,
    })
}

/// Maps a printable ASCII char to an evdev Key and a shift flag.
pub fn char_to_evdev(c: char) -> Option<(Key, bool)> {
    Some(match c {
        'a' => (Key::KEY_A, false),
        'A' => (Key::KEY_A, true),
        'b' => (Key::KEY_B, false),
        'B' => (Key::KEY_B, true),
        'c' => (Key::KEY_C, false),
        'C' => (Key::KEY_C, true),
        'd' => (Key::KEY_D, false),
        'D' => (Key::KEY_D, true),
        'e' => (Key::KEY_E, false),
        'E' => (Key::KEY_E, true),
        'f' => (Key::KEY_F, false),
        'F' => (Key::KEY_F, true),
        'g' => (Key::KEY_G, false),
        'G' => (Key::KEY_G, true),
        'h' => (Key::KEY_H, false),
        'H' => (Key::KEY_H, true),
        'i' => (Key::KEY_I, false),
        'I' => (Key::KEY_I, true),
        'j' => (Key::KEY_J, false),
        'J' => (Key::KEY_J, true),
        'k' => (Key::KEY_K, false),
        'K' => (Key::KEY_K, true),
        'l' => (Key::KEY_L, false),
        'L' => (Key::KEY_L, true),
        'm' => (Key::KEY_M, false),
        'M' => (Key::KEY_M, true),
        'n' => (Key::KEY_N, false),
        'N' => (Key::KEY_N, true),
        'o' => (Key::KEY_O, false),
        'O' => (Key::KEY_O, true),
        'p' => (Key::KEY_P, false),
        'P' => (Key::KEY_P, true),
        'q' => (Key::KEY_Q, false),
        'Q' => (Key::KEY_Q, true),
        'r' => (Key::KEY_R, false),
        'R' => (Key::KEY_R, true),
        's' => (Key::KEY_S, false),
        'S' => (Key::KEY_S, true),
        't' => (Key::KEY_T, false),
        'T' => (Key::KEY_T, true),
        'u' => (Key::KEY_U, false),
        'U' => (Key::KEY_U, true),
        'v' => (Key::KEY_V, false),
        'V' => (Key::KEY_V, true),
        'w' => (Key::KEY_W, false),
        'W' => (Key::KEY_W, true),
        'x' => (Key::KEY_X, false),
        'X' => (Key::KEY_X, true),
        'y' => (Key::KEY_Y, false),
        'Y' => (Key::KEY_Y, true),
        'z' => (Key::KEY_Z, false),
        'Z' => (Key::KEY_Z, true),
        '0' => (Key::KEY_0, false),
        '1' => (Key::KEY_1, false),
        '2' => (Key::KEY_2, false),
        '3' => (Key::KEY_3, false),
        '4' => (Key::KEY_4, false),
        '5' => (Key::KEY_5, false),
        '6' => (Key::KEY_6, false),
        '7' => (Key::KEY_7, false),
        '8' => (Key::KEY_8, false),
        '9' => (Key::KEY_9, false),
        ' ' => (Key::KEY_SPACE, false),
        '\n' => (Key::KEY_ENTER, false),
        '\t' => (Key::KEY_TAB, false),
        '-' => (Key::KEY_MINUS, false),
        '_' => (Key::KEY_MINUS, true),
        '=' => (Key::KEY_EQUAL, false),
        '+' => (Key::KEY_EQUAL, true),
        '[' => (Key::KEY_LEFTBRACE, false),
        '{' => (Key::KEY_LEFTBRACE, true),
        ']' => (Key::KEY_RIGHTBRACE, false),
        '}' => (Key::KEY_RIGHTBRACE, true),
        '\\' => (Key::KEY_BACKSLASH, false),
        '|' => (Key::KEY_BACKSLASH, true),
        ';' => (Key::KEY_SEMICOLON, false),
        ':' => (Key::KEY_SEMICOLON, true),
        '\'' => (Key::KEY_APOSTROPHE, false),
        '"' => (Key::KEY_APOSTROPHE, true),
        '`' => (Key::KEY_GRAVE, false),
        '~' => (Key::KEY_GRAVE, true),
        ',' => (Key::KEY_COMMA, false),
        '<' => (Key::KEY_COMMA, true),
        '.' => (Key::KEY_DOT, false),
        '>' => (Key::KEY_DOT, true),
        '/' => (Key::KEY_SLASH, false),
        '?' => (Key::KEY_SLASH, true),
        '!' => (Key::KEY_1, true),
        '@' => (Key::KEY_2, true),
        '#' => (Key::KEY_3, true),
        '$' => (Key::KEY_4, true),
        '%' => (Key::KEY_5, true),
        '^' => (Key::KEY_6, true),
        '&' => (Key::KEY_7, true),
        '*' => (Key::KEY_8, true),
        '(' => (Key::KEY_9, true),
        ')' => (Key::KEY_0, true),
        _ => return None,
    })
}
