use evdev::KeyCode;

use crate::input::types::MacroKey;

/// Maps an evdev Key (from a captured event) to our canonical MacroKey.
pub fn evdev_key_to_macro_key(key: KeyCode) -> Option<MacroKey> {
    Some(match key {
        KeyCode::KEY_A => MacroKey::Unicode('a'),
        KeyCode::KEY_B => MacroKey::Unicode('b'),
        KeyCode::KEY_C => MacroKey::Unicode('c'),
        KeyCode::KEY_D => MacroKey::Unicode('d'),
        KeyCode::KEY_E => MacroKey::Unicode('e'),
        KeyCode::KEY_F => MacroKey::Unicode('f'),
        KeyCode::KEY_G => MacroKey::Unicode('g'),
        KeyCode::KEY_H => MacroKey::Unicode('h'),
        KeyCode::KEY_I => MacroKey::Unicode('i'),
        KeyCode::KEY_J => MacroKey::Unicode('j'),
        KeyCode::KEY_K => MacroKey::Unicode('k'),
        KeyCode::KEY_L => MacroKey::Unicode('l'),
        KeyCode::KEY_M => MacroKey::Unicode('m'),
        KeyCode::KEY_N => MacroKey::Unicode('n'),
        KeyCode::KEY_O => MacroKey::Unicode('o'),
        KeyCode::KEY_P => MacroKey::Unicode('p'),
        KeyCode::KEY_Q => MacroKey::Unicode('q'),
        KeyCode::KEY_R => MacroKey::Unicode('r'),
        KeyCode::KEY_S => MacroKey::Unicode('s'),
        KeyCode::KEY_T => MacroKey::Unicode('t'),
        KeyCode::KEY_U => MacroKey::Unicode('u'),
        KeyCode::KEY_V => MacroKey::Unicode('v'),
        KeyCode::KEY_W => MacroKey::Unicode('w'),
        KeyCode::KEY_X => MacroKey::Unicode('x'),
        KeyCode::KEY_Y => MacroKey::Unicode('y'),
        KeyCode::KEY_Z => MacroKey::Unicode('z'),
        KeyCode::KEY_1 => MacroKey::Unicode('1'),
        KeyCode::KEY_2 => MacroKey::Unicode('2'),
        KeyCode::KEY_3 => MacroKey::Unicode('3'),
        KeyCode::KEY_4 => MacroKey::Unicode('4'),
        KeyCode::KEY_5 => MacroKey::Unicode('5'),
        KeyCode::KEY_6 => MacroKey::Unicode('6'),
        KeyCode::KEY_7 => MacroKey::Unicode('7'),
        KeyCode::KEY_8 => MacroKey::Unicode('8'),
        KeyCode::KEY_9 => MacroKey::Unicode('9'),
        KeyCode::KEY_0 => MacroKey::Unicode('0'),
        KeyCode::KEY_MINUS => MacroKey::Unicode('-'),
        KeyCode::KEY_EQUAL => MacroKey::Unicode('='),
        KeyCode::KEY_LEFTBRACE => MacroKey::Unicode('['),
        KeyCode::KEY_RIGHTBRACE => MacroKey::Unicode(']'),
        KeyCode::KEY_BACKSLASH => MacroKey::Unicode('\\'),
        KeyCode::KEY_SEMICOLON => MacroKey::Unicode(';'),
        KeyCode::KEY_APOSTROPHE => MacroKey::Unicode('\''),
        KeyCode::KEY_GRAVE => MacroKey::Unicode('`'),
        KeyCode::KEY_COMMA => MacroKey::Unicode(','),
        KeyCode::KEY_DOT => MacroKey::Unicode('.'),
        KeyCode::KEY_SLASH => MacroKey::Unicode('/'),
        KeyCode::KEY_ENTER => MacroKey::Return,
        KeyCode::KEY_BACKSPACE => MacroKey::Backspace,
        KeyCode::KEY_TAB => MacroKey::Tab,
        KeyCode::KEY_SPACE => MacroKey::Space,
        KeyCode::KEY_ESC => MacroKey::Escape,
        KeyCode::KEY_DELETE => MacroKey::Delete,
        KeyCode::KEY_INSERT => MacroKey::Insert,
        KeyCode::KEY_HOME => MacroKey::Home,
        KeyCode::KEY_END => MacroKey::End,
        KeyCode::KEY_PAGEUP => MacroKey::PageUp,
        KeyCode::KEY_PAGEDOWN => MacroKey::PageDown,
        KeyCode::KEY_UP => MacroKey::UpArrow,
        KeyCode::KEY_DOWN => MacroKey::DownArrow,
        KeyCode::KEY_LEFT => MacroKey::LeftArrow,
        KeyCode::KEY_RIGHT => MacroKey::RightArrow,
        KeyCode::KEY_LEFTSHIFT => MacroKey::LShift,
        KeyCode::KEY_RIGHTSHIFT => MacroKey::RShift,
        KeyCode::KEY_LEFTCTRL => MacroKey::LControl,
        KeyCode::KEY_RIGHTCTRL => MacroKey::RControl,
        KeyCode::KEY_LEFTALT => MacroKey::Alt,
        KeyCode::KEY_RIGHTALT => MacroKey::AltGr,
        KeyCode::KEY_LEFTMETA => MacroKey::Meta,
        KeyCode::KEY_RIGHTMETA => MacroKey::Meta,
        KeyCode::KEY_CAPSLOCK => MacroKey::CapsLock,
        KeyCode::KEY_NUMLOCK => MacroKey::NumLock,
        KeyCode::KEY_SCROLLLOCK => MacroKey::ScrollLock,
        KeyCode::KEY_PAUSE => MacroKey::Pause,
        KeyCode::KEY_SYSRQ => MacroKey::PrintScr,
        KeyCode::KEY_F1 => MacroKey::F1,
        KeyCode::KEY_F2 => MacroKey::F2,
        KeyCode::KEY_F3 => MacroKey::F3,
        KeyCode::KEY_F4 => MacroKey::F4,
        KeyCode::KEY_F5 => MacroKey::F5,
        KeyCode::KEY_F6 => MacroKey::F6,
        KeyCode::KEY_F7 => MacroKey::F7,
        KeyCode::KEY_F8 => MacroKey::F8,
        KeyCode::KEY_F9 => MacroKey::F9,
        KeyCode::KEY_F10 => MacroKey::F10,
        KeyCode::KEY_F11 => MacroKey::F11,
        KeyCode::KEY_F12 => MacroKey::F12,
        KeyCode::KEY_F13 => MacroKey::F13,
        KeyCode::KEY_F14 => MacroKey::F14,
        KeyCode::KEY_F15 => MacroKey::F15,
        KeyCode::KEY_F16 => MacroKey::F16,
        KeyCode::KEY_F17 => MacroKey::F17,
        KeyCode::KEY_F18 => MacroKey::F18,
        KeyCode::KEY_F19 => MacroKey::F19,
        KeyCode::KEY_F20 => MacroKey::F20,
        KeyCode::KEY_F21 => MacroKey::F21,
        KeyCode::KEY_F22 => MacroKey::F22,
        KeyCode::KEY_F23 => MacroKey::F23,
        KeyCode::KEY_F24 => MacroKey::F24,
        KeyCode::KEY_KP0 => MacroKey::Numpad0,
        KeyCode::KEY_KP1 => MacroKey::Numpad1,
        KeyCode::KEY_KP2 => MacroKey::Numpad2,
        KeyCode::KEY_KP3 => MacroKey::Numpad3,
        KeyCode::KEY_KP4 => MacroKey::Numpad4,
        KeyCode::KEY_KP5 => MacroKey::Numpad5,
        KeyCode::KEY_KP6 => MacroKey::Numpad6,
        KeyCode::KEY_KP7 => MacroKey::Numpad7,
        KeyCode::KEY_KP8 => MacroKey::Numpad8,
        KeyCode::KEY_KP9 => MacroKey::Numpad9,
        KeyCode::KEY_KPPLUS => MacroKey::Add,
        KeyCode::KEY_KPMINUS => MacroKey::Subtract,
        KeyCode::KEY_KPASTERISK => MacroKey::Multiply,
        KeyCode::KEY_KPSLASH => MacroKey::Divide,
        KeyCode::KEY_KPDOT => MacroKey::Decimal,
        KeyCode::KEY_VOLUMEDOWN => MacroKey::VolumeDown,
        KeyCode::KEY_MUTE => MacroKey::VolumeMute,
        KeyCode::KEY_VOLUMEUP => MacroKey::VolumeUp,
        KeyCode::BTN_LEFT => return None,   // handled as MacroButton
        KeyCode::BTN_RIGHT => return None,
        KeyCode::BTN_MIDDLE => return None,
        KeyCode::BTN_BACK | KeyCode::BTN_SIDE => return None,
        KeyCode::BTN_FORWARD | KeyCode::BTN_EXTRA => return None,
        _ => MacroKey::Other(key.0 as u32),
    })
}

/// Maps a MacroButton (from a captured mouse button event) to evdev key for re-emission.
pub fn evdev_button_from_code(code: u16) -> Option<crate::input::types::MacroButton> {
    use crate::input::types::MacroButton;
    Some(match KeyCode(code) {
        KeyCode::BTN_LEFT => MacroButton::Left,
        KeyCode::BTN_RIGHT => MacroButton::Right,
        KeyCode::BTN_MIDDLE => MacroButton::Middle,
        KeyCode::BTN_BACK | KeyCode::BTN_SIDE => MacroButton::Back,
        KeyCode::BTN_FORWARD | KeyCode::BTN_EXTRA => MacroButton::Forward,
        _ => return None,
    })
}

/// Maps our canonical MacroKey to an evdev Key for emission via uinput.
pub fn macro_key_to_evdev(key: &MacroKey) -> Option<(KeyCode, bool)> {
    Some(match key {
        MacroKey::Return => (KeyCode::KEY_ENTER, false),
        MacroKey::Backspace => (KeyCode::KEY_BACKSPACE, false),
        MacroKey::Tab => (KeyCode::KEY_TAB, false),
        MacroKey::Space => (KeyCode::KEY_SPACE, false),
        MacroKey::Escape => (KeyCode::KEY_ESC, false),
        MacroKey::Delete => (KeyCode::KEY_DELETE, false),
        MacroKey::Insert => (KeyCode::KEY_INSERT, false),
        MacroKey::Home => (KeyCode::KEY_HOME, false),
        MacroKey::End => (KeyCode::KEY_END, false),
        MacroKey::PageUp => (KeyCode::KEY_PAGEUP, false),
        MacroKey::PageDown => (KeyCode::KEY_PAGEDOWN, false),
        MacroKey::UpArrow => (KeyCode::KEY_UP, false),
        MacroKey::DownArrow => (KeyCode::KEY_DOWN, false),
        MacroKey::LeftArrow => (KeyCode::KEY_LEFT, false),
        MacroKey::RightArrow => (KeyCode::KEY_RIGHT, false),
        MacroKey::Shift | MacroKey::LShift => (KeyCode::KEY_LEFTSHIFT, false),
        MacroKey::RShift => (KeyCode::KEY_RIGHTSHIFT, false),
        MacroKey::Control | MacroKey::LControl => (KeyCode::KEY_LEFTCTRL, false),
        MacroKey::RControl => (KeyCode::KEY_RIGHTCTRL, false),
        MacroKey::Alt | MacroKey::Option => (KeyCode::KEY_LEFTALT, false),
        MacroKey::AltGr => (KeyCode::KEY_RIGHTALT, false),
        MacroKey::Meta => (KeyCode::KEY_LEFTMETA, false),
        MacroKey::CapsLock => (KeyCode::KEY_CAPSLOCK, false),
        MacroKey::NumLock => (KeyCode::KEY_NUMLOCK, false),
        MacroKey::ScrollLock => (KeyCode::KEY_SCROLLLOCK, false),
        MacroKey::Pause => (KeyCode::KEY_PAUSE, false),
        MacroKey::PrintScr => (KeyCode::KEY_SYSRQ, false),
        MacroKey::F1 => (KeyCode::KEY_F1, false),
        MacroKey::F2 => (KeyCode::KEY_F2, false),
        MacroKey::F3 => (KeyCode::KEY_F3, false),
        MacroKey::F4 => (KeyCode::KEY_F4, false),
        MacroKey::F5 => (KeyCode::KEY_F5, false),
        MacroKey::F6 => (KeyCode::KEY_F6, false),
        MacroKey::F7 => (KeyCode::KEY_F7, false),
        MacroKey::F8 => (KeyCode::KEY_F8, false),
        MacroKey::F9 => (KeyCode::KEY_F9, false),
        MacroKey::F10 => (KeyCode::KEY_F10, false),
        MacroKey::F11 => (KeyCode::KEY_F11, false),
        MacroKey::F12 => (KeyCode::KEY_F12, false),
        MacroKey::F13 => (KeyCode::KEY_F13, false),
        MacroKey::F14 => (KeyCode::KEY_F14, false),
        MacroKey::F15 => (KeyCode::KEY_F15, false),
        MacroKey::F16 => (KeyCode::KEY_F16, false),
        MacroKey::F17 => (KeyCode::KEY_F17, false),
        MacroKey::F18 => (KeyCode::KEY_F18, false),
        MacroKey::F19 => (KeyCode::KEY_F19, false),
        MacroKey::F20 => (KeyCode::KEY_F20, false),
        MacroKey::F21 => (KeyCode::KEY_F21, false),
        MacroKey::F22 => (KeyCode::KEY_F22, false),
        MacroKey::F23 => (KeyCode::KEY_F23, false),
        MacroKey::F24 => (KeyCode::KEY_F24, false),
        MacroKey::Numpad0 => (KeyCode::KEY_KP0, false),
        MacroKey::Numpad1 => (KeyCode::KEY_KP1, false),
        MacroKey::Numpad2 => (KeyCode::KEY_KP2, false),
        MacroKey::Numpad3 => (KeyCode::KEY_KP3, false),
        MacroKey::Numpad4 => (KeyCode::KEY_KP4, false),
        MacroKey::Numpad5 => (KeyCode::KEY_KP5, false),
        MacroKey::Numpad6 => (KeyCode::KEY_KP6, false),
        MacroKey::Numpad7 => (KeyCode::KEY_KP7, false),
        MacroKey::Numpad8 => (KeyCode::KEY_KP8, false),
        MacroKey::Numpad9 => (KeyCode::KEY_KP9, false),
        MacroKey::Add => (KeyCode::KEY_KPPLUS, false),
        MacroKey::Subtract => (KeyCode::KEY_KPMINUS, false),
        MacroKey::Multiply => (KeyCode::KEY_KPASTERISK, false),
        MacroKey::Divide => (KeyCode::KEY_KPSLASH, false),
        MacroKey::Decimal => (KeyCode::KEY_KPDOT, false),
        MacroKey::VolumeDown => (KeyCode::KEY_VOLUMEDOWN, false),
        MacroKey::VolumeMute => (KeyCode::KEY_MUTE, false),
        MacroKey::VolumeUp => (KeyCode::KEY_VOLUMEUP, false),
        MacroKey::LMenu => (KeyCode::KEY_LEFTMETA, false),
        MacroKey::Select => (KeyCode::KEY_SELECT, false),
        MacroKey::Unicode(c) => char_to_evdev(*c)?,
        MacroKey::Other(n) => (KeyCode(*n as u16), false),
    })
}

/// Maps a MacroButton to the corresponding evdev Key code for emission.
pub fn macro_button_to_evdev(button: &crate::input::types::MacroButton) -> Option<KeyCode> {
    use crate::input::types::MacroButton;
    Some(match button {
        MacroButton::Left => KeyCode::BTN_LEFT,
        MacroButton::Right => KeyCode::BTN_RIGHT,
        MacroButton::Middle => KeyCode::BTN_MIDDLE,
        MacroButton::Back => KeyCode::BTN_BACK,
        MacroButton::Forward => KeyCode::BTN_FORWARD,
        MacroButton::Other(n) => KeyCode(*n as u16),
        // Scroll variants are emitted as REL_WHEEL, not KEY events
        MacroButton::ScrollUp
        | MacroButton::ScrollDown
        | MacroButton::ScrollLeft
        | MacroButton::ScrollRight => return None,
    })
}

/// Maps a printable ASCII char to an evdev Key and a shift flag.
pub fn char_to_evdev(c: char) -> Option<(KeyCode, bool)> {
    Some(match c {
        'a' => (KeyCode::KEY_A, false),
        'A' => (KeyCode::KEY_A, true),
        'b' => (KeyCode::KEY_B, false),
        'B' => (KeyCode::KEY_B, true),
        'c' => (KeyCode::KEY_C, false),
        'C' => (KeyCode::KEY_C, true),
        'd' => (KeyCode::KEY_D, false),
        'D' => (KeyCode::KEY_D, true),
        'e' => (KeyCode::KEY_E, false),
        'E' => (KeyCode::KEY_E, true),
        'f' => (KeyCode::KEY_F, false),
        'F' => (KeyCode::KEY_F, true),
        'g' => (KeyCode::KEY_G, false),
        'G' => (KeyCode::KEY_G, true),
        'h' => (KeyCode::KEY_H, false),
        'H' => (KeyCode::KEY_H, true),
        'i' => (KeyCode::KEY_I, false),
        'I' => (KeyCode::KEY_I, true),
        'j' => (KeyCode::KEY_J, false),
        'J' => (KeyCode::KEY_J, true),
        'k' => (KeyCode::KEY_K, false),
        'K' => (KeyCode::KEY_K, true),
        'l' => (KeyCode::KEY_L, false),
        'L' => (KeyCode::KEY_L, true),
        'm' => (KeyCode::KEY_M, false),
        'M' => (KeyCode::KEY_M, true),
        'n' => (KeyCode::KEY_N, false),
        'N' => (KeyCode::KEY_N, true),
        'o' => (KeyCode::KEY_O, false),
        'O' => (KeyCode::KEY_O, true),
        'p' => (KeyCode::KEY_P, false),
        'P' => (KeyCode::KEY_P, true),
        'q' => (KeyCode::KEY_Q, false),
        'Q' => (KeyCode::KEY_Q, true),
        'r' => (KeyCode::KEY_R, false),
        'R' => (KeyCode::KEY_R, true),
        's' => (KeyCode::KEY_S, false),
        'S' => (KeyCode::KEY_S, true),
        't' => (KeyCode::KEY_T, false),
        'T' => (KeyCode::KEY_T, true),
        'u' => (KeyCode::KEY_U, false),
        'U' => (KeyCode::KEY_U, true),
        'v' => (KeyCode::KEY_V, false),
        'V' => (KeyCode::KEY_V, true),
        'w' => (KeyCode::KEY_W, false),
        'W' => (KeyCode::KEY_W, true),
        'x' => (KeyCode::KEY_X, false),
        'X' => (KeyCode::KEY_X, true),
        'y' => (KeyCode::KEY_Y, false),
        'Y' => (KeyCode::KEY_Y, true),
        'z' => (KeyCode::KEY_Z, false),
        'Z' => (KeyCode::KEY_Z, true),
        '0' => (KeyCode::KEY_0, false),
        '1' => (KeyCode::KEY_1, false),
        '2' => (KeyCode::KEY_2, false),
        '3' => (KeyCode::KEY_3, false),
        '4' => (KeyCode::KEY_4, false),
        '5' => (KeyCode::KEY_5, false),
        '6' => (KeyCode::KEY_6, false),
        '7' => (KeyCode::KEY_7, false),
        '8' => (KeyCode::KEY_8, false),
        '9' => (KeyCode::KEY_9, false),
        ' ' => (KeyCode::KEY_SPACE, false),
        '\n' => (KeyCode::KEY_ENTER, false),
        '\t' => (KeyCode::KEY_TAB, false),
        '-' => (KeyCode::KEY_MINUS, false),
        '_' => (KeyCode::KEY_MINUS, true),
        '=' => (KeyCode::KEY_EQUAL, false),
        '+' => (KeyCode::KEY_EQUAL, true),
        '[' => (KeyCode::KEY_LEFTBRACE, false),
        '{' => (KeyCode::KEY_LEFTBRACE, true),
        ']' => (KeyCode::KEY_RIGHTBRACE, false),
        '}' => (KeyCode::KEY_RIGHTBRACE, true),
        '\\' => (KeyCode::KEY_BACKSLASH, false),
        '|' => (KeyCode::KEY_BACKSLASH, true),
        ';' => (KeyCode::KEY_SEMICOLON, false),
        ':' => (KeyCode::KEY_SEMICOLON, true),
        '\'' => (KeyCode::KEY_APOSTROPHE, false),
        '"' => (KeyCode::KEY_APOSTROPHE, true),
        '`' => (KeyCode::KEY_GRAVE, false),
        '~' => (KeyCode::KEY_GRAVE, true),
        ',' => (KeyCode::KEY_COMMA, false),
        '<' => (KeyCode::KEY_COMMA, true),
        '.' => (KeyCode::KEY_DOT, false),
        '>' => (KeyCode::KEY_DOT, true),
        '/' => (KeyCode::KEY_SLASH, false),
        '?' => (KeyCode::KEY_SLASH, true),
        '!' => (KeyCode::KEY_1, true),
        '@' => (KeyCode::KEY_2, true),
        '#' => (KeyCode::KEY_3, true),
        '$' => (KeyCode::KEY_4, true),
        '%' => (KeyCode::KEY_5, true),
        '^' => (KeyCode::KEY_6, true),
        '&' => (KeyCode::KEY_7, true),
        '*' => (KeyCode::KEY_8, true),
        '(' => (KeyCode::KEY_9, true),
        ')' => (KeyCode::KEY_0, true),
        _ => return None,
    })
}
