use enigo::{Button, Key as EnigoKey};
use rdev::{Button as RdevButton, Key as RdevKey};

/// Maps an enigo Key to an rdev Key and a flag indicating whether Left Shift must be held.
pub fn enigo_key_to_rdev(key: &EnigoKey) -> Option<(RdevKey, bool)> {
    match key {
        EnigoKey::Return => Some((RdevKey::Return, false)),
        EnigoKey::Backspace => Some((RdevKey::Backspace, false)),
        EnigoKey::Tab => Some((RdevKey::Tab, false)),
        EnigoKey::Space => Some((RdevKey::Space, false)),
        EnigoKey::Escape => Some((RdevKey::Escape, false)),
        EnigoKey::Delete => Some((RdevKey::Delete, false)),
        EnigoKey::Insert => Some((RdevKey::Insert, false)),
        EnigoKey::Home => Some((RdevKey::Home, false)),
        EnigoKey::End => Some((RdevKey::End, false)),
        EnigoKey::PageUp => Some((RdevKey::PageUp, false)),
        EnigoKey::PageDown => Some((RdevKey::PageDown, false)),
        EnigoKey::UpArrow => Some((RdevKey::UpArrow, false)),
        EnigoKey::DownArrow => Some((RdevKey::DownArrow, false)),
        EnigoKey::LeftArrow => Some((RdevKey::LeftArrow, false)),
        EnigoKey::RightArrow => Some((RdevKey::RightArrow, false)),
        EnigoKey::Shift | EnigoKey::LShift => Some((RdevKey::ShiftLeft, false)),
        EnigoKey::RShift => Some((RdevKey::ShiftRight, false)),
        EnigoKey::Control | EnigoKey::LControl => Some((RdevKey::ControlLeft, false)),
        EnigoKey::RControl => Some((RdevKey::ControlRight, false)),
        EnigoKey::Alt => Some((RdevKey::Alt, false)),
        EnigoKey::Meta => Some((RdevKey::MetaLeft, false)),
        EnigoKey::CapsLock => Some((RdevKey::CapsLock, false)),
        EnigoKey::Numlock => Some((RdevKey::NumLock, false)),
        EnigoKey::ScrollLock => Some((RdevKey::ScrollLock, false)),
        EnigoKey::Pause => Some((RdevKey::Pause, false)),
        EnigoKey::PrintScr => Some((RdevKey::PrintScreen, false)),
        EnigoKey::F1 => Some((RdevKey::F1, false)),
        EnigoKey::F2 => Some((RdevKey::F2, false)),
        EnigoKey::F3 => Some((RdevKey::F3, false)),
        EnigoKey::F4 => Some((RdevKey::F4, false)),
        EnigoKey::F5 => Some((RdevKey::F5, false)),
        EnigoKey::F6 => Some((RdevKey::F6, false)),
        EnigoKey::F7 => Some((RdevKey::F7, false)),
        EnigoKey::F8 => Some((RdevKey::F8, false)),
        EnigoKey::F9 => Some((RdevKey::F9, false)),
        EnigoKey::F10 => Some((RdevKey::F10, false)),
        EnigoKey::F11 => Some((RdevKey::F11, false)),
        EnigoKey::F12 => Some((RdevKey::F12, false)),
        EnigoKey::Numpad0 => Some((RdevKey::Kp0, false)),
        EnigoKey::Numpad1 => Some((RdevKey::Kp1, false)),
        EnigoKey::Numpad2 => Some((RdevKey::Kp2, false)),
        EnigoKey::Numpad3 => Some((RdevKey::Kp3, false)),
        EnigoKey::Numpad4 => Some((RdevKey::Kp4, false)),
        EnigoKey::Numpad5 => Some((RdevKey::Kp5, false)),
        EnigoKey::Numpad6 => Some((RdevKey::Kp6, false)),
        EnigoKey::Numpad7 => Some((RdevKey::Kp7, false)),
        EnigoKey::Numpad8 => Some((RdevKey::Kp8, false)),
        EnigoKey::Numpad9 => Some((RdevKey::Kp9, false)),
        EnigoKey::Add => Some((RdevKey::KpPlus, false)),
        EnigoKey::Subtract => Some((RdevKey::KpMinus, false)),
        EnigoKey::Multiply => Some((RdevKey::KpMultiply, false)),
        EnigoKey::Divide => Some((RdevKey::KpDivide, false)),
        EnigoKey::Decimal => Some((RdevKey::KpDelete, false)),
        EnigoKey::Unicode(c) => char_to_rdev(*c),
        EnigoKey::Other(n) => Some((RdevKey::Unknown(*n), false)),
        _ => None,
    }
}

/// Maps an enigo Button to an rdev Button. Scroll variants return None (handled as Wheel events).
pub fn enigo_button_to_rdev(button: Button) -> Option<RdevButton> {
    match button {
        Button::Left => Some(RdevButton::Left),
        Button::Right => Some(RdevButton::Right),
        Button::Middle => Some(RdevButton::Middle),
        Button::Back => Some(RdevButton::Unknown(8)),
        Button::Forward => Some(RdevButton::Unknown(9)),
        _ => None,
    }
}

/// Maps a printable ASCII character to an rdev key and shift flag.
pub fn char_to_rdev(c: char) -> Option<(RdevKey, bool)> {
    match c {
        'a' => Some((RdevKey::KeyA, false)),
        'A' => Some((RdevKey::KeyA, true)),
        'b' => Some((RdevKey::KeyB, false)),
        'B' => Some((RdevKey::KeyB, true)),
        'c' => Some((RdevKey::KeyC, false)),
        'C' => Some((RdevKey::KeyC, true)),
        'd' => Some((RdevKey::KeyD, false)),
        'D' => Some((RdevKey::KeyD, true)),
        'e' => Some((RdevKey::KeyE, false)),
        'E' => Some((RdevKey::KeyE, true)),
        'f' => Some((RdevKey::KeyF, false)),
        'F' => Some((RdevKey::KeyF, true)),
        'g' => Some((RdevKey::KeyG, false)),
        'G' => Some((RdevKey::KeyG, true)),
        'h' => Some((RdevKey::KeyH, false)),
        'H' => Some((RdevKey::KeyH, true)),
        'i' => Some((RdevKey::KeyI, false)),
        'I' => Some((RdevKey::KeyI, true)),
        'j' => Some((RdevKey::KeyJ, false)),
        'J' => Some((RdevKey::KeyJ, true)),
        'k' => Some((RdevKey::KeyK, false)),
        'K' => Some((RdevKey::KeyK, true)),
        'l' => Some((RdevKey::KeyL, false)),
        'L' => Some((RdevKey::KeyL, true)),
        'm' => Some((RdevKey::KeyM, false)),
        'M' => Some((RdevKey::KeyM, true)),
        'n' => Some((RdevKey::KeyN, false)),
        'N' => Some((RdevKey::KeyN, true)),
        'o' => Some((RdevKey::KeyO, false)),
        'O' => Some((RdevKey::KeyO, true)),
        'p' => Some((RdevKey::KeyP, false)),
        'P' => Some((RdevKey::KeyP, true)),
        'q' => Some((RdevKey::KeyQ, false)),
        'Q' => Some((RdevKey::KeyQ, true)),
        'r' => Some((RdevKey::KeyR, false)),
        'R' => Some((RdevKey::KeyR, true)),
        's' => Some((RdevKey::KeyS, false)),
        'S' => Some((RdevKey::KeyS, true)),
        't' => Some((RdevKey::KeyT, false)),
        'T' => Some((RdevKey::KeyT, true)),
        'u' => Some((RdevKey::KeyU, false)),
        'U' => Some((RdevKey::KeyU, true)),
        'v' => Some((RdevKey::KeyV, false)),
        'V' => Some((RdevKey::KeyV, true)),
        'w' => Some((RdevKey::KeyW, false)),
        'W' => Some((RdevKey::KeyW, true)),
        'x' => Some((RdevKey::KeyX, false)),
        'X' => Some((RdevKey::KeyX, true)),
        'y' => Some((RdevKey::KeyY, false)),
        'Y' => Some((RdevKey::KeyY, true)),
        'z' => Some((RdevKey::KeyZ, false)),
        'Z' => Some((RdevKey::KeyZ, true)),
        '0' => Some((RdevKey::Num0, false)),
        '1' => Some((RdevKey::Num1, false)),
        '2' => Some((RdevKey::Num2, false)),
        '3' => Some((RdevKey::Num3, false)),
        '4' => Some((RdevKey::Num4, false)),
        '5' => Some((RdevKey::Num5, false)),
        '6' => Some((RdevKey::Num6, false)),
        '7' => Some((RdevKey::Num7, false)),
        '8' => Some((RdevKey::Num8, false)),
        '9' => Some((RdevKey::Num9, false)),
        ' ' => Some((RdevKey::Space, false)),
        '\n' => Some((RdevKey::Return, false)),
        '\t' => Some((RdevKey::Tab, false)),
        '-' => Some((RdevKey::Minus, false)),
        '_' => Some((RdevKey::Minus, true)),
        '=' => Some((RdevKey::Equal, false)),
        '+' => Some((RdevKey::Equal, true)),
        '[' => Some((RdevKey::LeftBracket, false)),
        '{' => Some((RdevKey::LeftBracket, true)),
        ']' => Some((RdevKey::RightBracket, false)),
        '}' => Some((RdevKey::RightBracket, true)),
        '\\' => Some((RdevKey::BackSlash, false)),
        '|' => Some((RdevKey::BackSlash, true)),
        ';' => Some((RdevKey::SemiColon, false)),
        ':' => Some((RdevKey::SemiColon, true)),
        '\'' => Some((RdevKey::Quote, false)),
        '"' => Some((RdevKey::Quote, true)),
        '`' => Some((RdevKey::BackQuote, false)),
        '~' => Some((RdevKey::BackQuote, true)),
        ',' => Some((RdevKey::Comma, false)),
        '<' => Some((RdevKey::Comma, true)),
        '.' => Some((RdevKey::Dot, false)),
        '>' => Some((RdevKey::Dot, true)),
        '/' => Some((RdevKey::Slash, false)),
        '?' => Some((RdevKey::Slash, true)),
        '!' => Some((RdevKey::Num1, true)),
        '@' => Some((RdevKey::Num2, true)),
        '#' => Some((RdevKey::Num3, true)),
        '$' => Some((RdevKey::Num4, true)),
        '%' => Some((RdevKey::Num5, true)),
        '^' => Some((RdevKey::Num6, true)),
        '&' => Some((RdevKey::Num7, true)),
        '*' => Some((RdevKey::Num8, true)),
        '(' => Some((RdevKey::Num9, true)),
        ')' => Some((RdevKey::Num0, true)),
        _ => None,
    }
}
