[package]
name = "macros-linux-bridge"
version.workspace = true
edition.workspace = true

[[bin]]
name = "macros-linux-bridge"
path = "src/main.rs"

[dependencies]
macros-core = { path = "../macros-core", default-features = false }
evdev.workspace = true
memmap2.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
