[package]
name = "blockwork-linux-bridge"
version.workspace = true
edition.workspace = true

[[bin]]
name = "blockwork-linux-bridge"
path = "src/main.rs"

[dependencies]
blockwork-core = { path = "../blockwork-core", default-features = false }
evdev.workspace = true
memmap2.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
