use enigo::{Button as EnigoButton, Key as EnigoKey};
use rdev::{Button as RdevButton, Key as RdevKey};

pub(crate) fn map_rdev_key(key: RdevKey) -> Option<EnigoKey> {
    match key {
        RdevKey::Alt => Some(EnigoKey::Alt),
        RdevKey::AltGr => Some(EnigoKey::Alt),
        RdevKey::Backspace => Some(EnigoKey::Backspace),
        RdevKey::CapsLock => Some(EnigoKey::CapsLock),
        RdevKey::ControlLeft => Some(EnigoKey::LControl),
        RdevKey::ControlRight => Some(EnigoKey::RControl),
        RdevKey::Delete => Some(EnigoKey::Delete),
        RdevKey::DownArrow => Some(EnigoKey::DownArrow),
        RdevKey::End => Some(EnigoKey::End),
        RdevKey::Escape => Some(EnigoKey::Escape),
        RdevKey::F1 => Some(EnigoKey::F1),
        RdevKey::F2 => Some(EnigoKey::F2),
        RdevKey::F3 => Some(EnigoKey::F3),
        RdevKey::F4 => Some(EnigoKey::F4),
        RdevKey::F5 => Some(EnigoKey::F5),
        RdevKey::F6 => Some(EnigoKey::F6),
        RdevKey::F7 => Some(EnigoKey::F7),
        RdevKey::F8 => Some(EnigoKey::F8),
        RdevKey::F9 => Some(EnigoKey::F9),
        RdevKey::F10 => Some(EnigoKey::F10),
        RdevKey::F11 => Some(EnigoKey::F11),
        RdevKey::F12 => Some(EnigoKey::F12),
        RdevKey::Home => Some(EnigoKey::Home),
        RdevKey::LeftArrow => Some(EnigoKey::LeftArrow),
        RdevKey::MetaLeft => Some(EnigoKey::Meta),
        RdevKey::MetaRight => Some(EnigoKey::Meta),
        RdevKey::PageDown => Some(EnigoKey::PageDown),
        RdevKey::PageUp => Some(EnigoKey::PageUp),
        RdevKey::Return => Some(EnigoKey::Return),
        RdevKey::RightArrow => Some(EnigoKey::RightArrow),
        RdevKey::ShiftLeft => Some(EnigoKey::LShift),
        RdevKey::ShiftRight => Some(EnigoKey::RShift),
        RdevKey::Space => Some(EnigoKey::Space),
        RdevKey::Tab => Some(EnigoKey::Tab),
        RdevKey::UpArrow => Some(EnigoKey::UpArrow),
        RdevKey::PrintScreen => Some(EnigoKey::PrintScr),
        #[cfg(all(unix, not(target_os = "macos")))]
        RdevKey::ScrollLock => Some(EnigoKey::ScrollLock),
        #[cfg(target_os = "windows")]
        RdevKey::ScrollLock => Some(EnigoKey::Scroll),
        RdevKey::Pause => Some(EnigoKey::Pause),
        RdevKey::NumLock => Some(EnigoKey::Numlock),
        RdevKey::Insert => Some(EnigoKey::Insert),
        RdevKey::KeyA => Some(EnigoKey::Unicode('a')),
        RdevKey::KeyB => Some(EnigoKey::Unicode('b')),
        RdevKey::KeyC => Some(EnigoKey::Unicode('c')),
        RdevKey::KeyD => Some(EnigoKey::Unicode('d')),
        RdevKey::KeyE => Some(EnigoKey::Unicode('e')),
        RdevKey::KeyF => Some(EnigoKey::Unicode('f')),
        RdevKey::KeyG => Some(EnigoKey::Unicode('g')),
        RdevKey::KeyH => Some(EnigoKey::Unicode('h')),
        RdevKey::KeyI => Some(EnigoKey::Unicode('i')),
        RdevKey::KeyJ => Some(EnigoKey::Unicode('j')),
        RdevKey::KeyK => Some(EnigoKey::Unicode('k')),
        RdevKey::KeyL => Some(EnigoKey::Unicode('l')),
        RdevKey::KeyM => Some(EnigoKey::Unicode('m')),
        RdevKey::KeyN => Some(EnigoKey::Unicode('n')),
        RdevKey::KeyO => Some(EnigoKey::Unicode('o')),
        RdevKey::KeyP => Some(EnigoKey::Unicode('p')),
        RdevKey::KeyQ => Some(EnigoKey::Unicode('q')),
        RdevKey::KeyR => Some(EnigoKey::Unicode('r')),
        RdevKey::KeyS => Some(EnigoKey::Unicode('s')),
        RdevKey::KeyT => Some(EnigoKey::Unicode('t')),
        RdevKey::KeyU => Some(EnigoKey::Unicode('u')),
        RdevKey::KeyV => Some(EnigoKey::Unicode('v')),
        RdevKey::KeyW => Some(EnigoKey::Unicode('w')),
        RdevKey::KeyX => Some(EnigoKey::Unicode('x')),
        RdevKey::KeyY => Some(EnigoKey::Unicode('y')),
        RdevKey::KeyZ => Some(EnigoKey::Unicode('z')),
        RdevKey::Num0 => Some(EnigoKey::Unicode('0')),
        RdevKey::Num1 => Some(EnigoKey::Unicode('1')),
        RdevKey::Num2 => Some(EnigoKey::Unicode('2')),
        RdevKey::Num3 => Some(EnigoKey::Unicode('3')),
        RdevKey::Num4 => Some(EnigoKey::Unicode('4')),
        RdevKey::Num5 => Some(EnigoKey::Unicode('5')),
        RdevKey::Num6 => Some(EnigoKey::Unicode('6')),
        RdevKey::Num7 => Some(EnigoKey::Unicode('7')),
        RdevKey::Num8 => Some(EnigoKey::Unicode('8')),
        RdevKey::Num9 => Some(EnigoKey::Unicode('9')),
        RdevKey::BackQuote => Some(EnigoKey::Unicode('`')),
        RdevKey::Minus => Some(EnigoKey::Unicode('-')),
        RdevKey::Equal => Some(EnigoKey::Unicode('=')),
        RdevKey::LeftBracket => Some(EnigoKey::Unicode('[')),
        RdevKey::RightBracket => Some(EnigoKey::Unicode(']')),
        RdevKey::SemiColon => Some(EnigoKey::Unicode(';')),
        RdevKey::Quote => Some(EnigoKey::Unicode('\'')),
        RdevKey::BackSlash | RdevKey::IntlBackslash => Some(EnigoKey::Unicode('\\')),
        RdevKey::Comma => Some(EnigoKey::Unicode(',')),
        RdevKey::Dot => Some(EnigoKey::Unicode('.')),
        RdevKey::Slash => Some(EnigoKey::Unicode('/')),
        RdevKey::KpReturn => Some(EnigoKey::Return),
        RdevKey::KpMinus => Some(EnigoKey::Unicode('-')),
        RdevKey::KpPlus => Some(EnigoKey::Unicode('+')),
        RdevKey::KpMultiply => Some(EnigoKey::Unicode('*')),
        RdevKey::KpDivide => Some(EnigoKey::Unicode('/')),
        RdevKey::Kp0 => Some(EnigoKey::Unicode('0')),
        RdevKey::Kp1 => Some(EnigoKey::Unicode('1')),
        RdevKey::Kp2 => Some(EnigoKey::Unicode('2')),
        RdevKey::Kp3 => Some(EnigoKey::Unicode('3')),
        RdevKey::Kp4 => Some(EnigoKey::Unicode('4')),
        RdevKey::Kp5 => Some(EnigoKey::Unicode('5')),
        RdevKey::Kp6 => Some(EnigoKey::Unicode('6')),
        RdevKey::Kp7 => Some(EnigoKey::Unicode('7')),
        RdevKey::Kp8 => Some(EnigoKey::Unicode('8')),
        RdevKey::Kp9 => Some(EnigoKey::Unicode('9')),
        RdevKey::KpDelete => Some(EnigoKey::Delete),
        RdevKey::Function | RdevKey::Unknown(_) => None,
    }
}

pub(crate) fn map_rdev_button(btn: RdevButton) -> Option<EnigoButton> {
    match btn {
        RdevButton::Left => Some(EnigoButton::Left),
        RdevButton::Right => Some(EnigoButton::Right),
        RdevButton::Middle => Some(EnigoButton::Middle),
        RdevButton::Unknown(_) => None,
    }
}
